// <auto-generated />
using System;
using CanteenApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CanteenApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727171336_AddDepartment")]
    partial class AddDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CanteenApi.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TicketDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("CanteenApi.Models.BillingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BillingPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BillingPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BreakfastAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("BreakfastCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("DinnerAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("DinnerCount")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LunchAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("LunchCount")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("BillingRecords");
                });

            modelBuilder.Entity("CanteenApi.Models.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveEmployees")
                        .HasColumnType("integer");

                    b.Property<int>("BreakfastCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("BreakfastRevenue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DinnerCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("DinnerRevenue")
                        .HasColumnType("numeric");

                    b.Property<int>("LunchCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("LunchRevenue")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("SummaryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMealsServed")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("CanteenApi.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 27, 17, 13, 34, 118, DateTimeKind.Utc).AddTicks(6595),
                            Description = "Information Technology",
                            IsActive = true,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 27, 17, 13, 34, 118, DateTimeKind.Utc).AddTicks(6599),
                            Description = "Human Capital",
                            IsActive = true,
                            Name = "HC"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 27, 17, 13, 34, 118, DateTimeKind.Utc).AddTicks(6602),
                            Description = "Finance Department",
                            IsActive = true,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 27, 17, 13, 34, 118, DateTimeKind.Utc).AddTicks(6605),
                            Description = "Operations & Logistics",
                            IsActive = true,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 27, 17, 13, 34, 118, DateTimeKind.Utc).AddTicks(6607),
                            Description = "Marketing & Sales",
                            IsActive = true,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("CanteenApi.Models.MealTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("QRCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TicketDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BatchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("MealTickets");
                });

            modelBuilder.Entity("CanteenApi.Models.Reconciliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BreakfastIssued")
                        .HasColumnType("integer");

                    b.Property<int>("BreakfastRedeemed")
                        .HasColumnType("integer");

                    b.Property<int>("BreakfastVariance")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentBreakdown")
                        .HasColumnType("text");

                    b.Property<int>("DinnerIssued")
                        .HasColumnType("integer");

                    b.Property<int>("DinnerRedeemed")
                        .HasColumnType("integer");

                    b.Property<int>("DinnerVariance")
                        .HasColumnType("integer");

                    b.Property<int>("LunchIssued")
                        .HasColumnType("integer");

                    b.Property<int>("LunchRedeemed")
                        .HasColumnType("integer");

                    b.Property<int>("LunchVariance")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReconciledBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReconciliationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalTicketsIssued")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTicketsPending")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTicketsRedeemed")
                        .HasColumnType("integer");

                    b.Property<int>("Variance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReconciledBy");

                    b.ToTable("Reconciliations");
                });

            modelBuilder.Entity("CanteenApi.Models.RedemptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChefId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RedemptionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChefId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RedemptionLogs");
                });

            modelBuilder.Entity("CanteenApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 27, 17, 13, 34, 118, DateTimeKind.Utc).AddTicks(7105),
                            DepartmentId = 1,
                            Email = "admin@masimba.co.zw",
                            EmployeeCode = "ADMIN001",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "QWRtaW5AMTIz",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CanteenApi.Models.Batch", b =>
                {
                    b.HasOne("CanteenApi.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CanteenApi.Models.BillingRecord", b =>
                {
                    b.HasOne("CanteenApi.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CanteenApi.Models.MealTicket", b =>
                {
                    b.HasOne("CanteenApi.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("CanteenApi.Models.Batch", "Batch")
                        .WithMany("Tickets")
                        .HasForeignKey("BatchId");

                    b.HasOne("CanteenApi.Models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Approver");

                    b.Navigation("Batch");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CanteenApi.Models.Reconciliation", b =>
                {
                    b.HasOne("CanteenApi.Models.User", "Reconciler")
                        .WithMany()
                        .HasForeignKey("ReconciledBy");

                    b.Navigation("Reconciler");
                });

            modelBuilder.Entity("CanteenApi.Models.RedemptionLog", b =>
                {
                    b.HasOne("CanteenApi.Models.User", "Chef")
                        .WithMany()
                        .HasForeignKey("ChefId");

                    b.HasOne("CanteenApi.Models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Chef");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CanteenApi.Models.User", b =>
                {
                    b.HasOne("CanteenApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CanteenApi.Models.Batch", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CanteenApi.Models.Department", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
